replicaCount: 1

image:
  repository: 667950714614.dkr.ecr.us-east-2.amazonaws.com/social-activity-stats
  pullPolicy: Always
  tag: "prod"

fullnameOverride: "social-activity-stats"
containerPort: 5000

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

autoscaling: {}

env:
    ENV: ""
    
