replicaCount: 1

image:
  repository: 667950714614.dkr.ecr.us-east-1.amazonaws.com/discord-activity-to-mixpanel
  pullPolicy: Always
  tag: "latest"

fullnameOverride: "discord-activity-to-mixpanel"
containerPort: 5000

resources:
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "core"
    effect: "NoSchedule"

env:
      TWITTER_MIXPANEL_SERVICE_ACCOUNT_SECRET:
      TWITTER_MIXPANEL_SERVICE_ACCOUNT:
      TWITTER_MIXPANEL_PROJECT_ID:

  